services:
  app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongo:27017/go-auth
      - SECRET_KEY=your-super-secret-jwt-key-here-make-it-long-and-random
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/api-1"]
      interval: 30s
      timeout: 10s
      retries: 3
    stop_grace_period: 15s

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 10s

volumes:
  mongo_data:
